# Site settings
title: Ryan Latta
email: latta.ryan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Building software is hard. Actually getting results can seem impossible.
    I am interested in exploring what it takes to delivering software that
    has meaningful impact for customers, users, and businesses. I bring lean
    and agile tools and thinking to groups and teams so they can find a way
    to continually improve and relentlessly pursue meaningful results.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryanlatta.com" # the base hostname & protocol for your site
twitter_username: recursivefaults
github_username:  recursivefaults

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
