# Site settings
title: Ryan Latta
email: ryan@ryanlatta.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Latta is a consultant that specalizes in creating high-performing software groups, and coaches
  developers through their careers. Here you'll find offerings, products, and articles to help you
  transform your group and your career.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ryanlatta.com" # the base hostname & protocol for your site
twitter_username: recursivefaults
github_username:  recursivefaults

#Collections
collections:
  - workshops

plugins:
    - jekyll-feed
    - jekyll-paginate-v2

feed:
    tags:
      path: "/feed/tags/"
      only:
        - newsletter
    categories:
        - career
        - consulting

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

permalink: /:year/:month/:title.html

defaults:
    -
      scope:
        path: "" # an empty string here means all files in the project
        type: "posts" # previously `post` in Jekyll 2.2.
      values:
        layout: "post" 
        category: "consulting" 
    - scope:
        path: ""
        type: "page"
      values:
        cta_text: Join Now!
        cta_url: https://bost.link/UmkgWn
        lead_text: Be the first to know about my tips, webinars, and offers
    - scope:
        path: ""
        category: "career"
      values:
        lead_text: "Subscribe and get a free chapter on salary negotiation!"
        cta_text: Join Now!
        cta_url: https://bost.link/a05rzK
    - scope:
        path: ""
        category: "consulting"
      values:
        cta_text: Subscribe!
        cta_url: https://bost.link/UmkgWn
        lead_text: Be the first to know about my tips, webinars, and offers

pagination:
  enabled: true
  per_page: 6
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layouts: 
      - 'autopages-tags.html'
    permalink: '/tag/:tag'

